package main

import (
	"bytes"
	"io"
	"net/http"
	"net/http/httptest"
	"testing"

	"github.com/theolujay/snippetbox/internal/assert"
)

func TestPing(t *testing.T) {
	// Initialize a new httptest.ResponseRecorder
	rr := httptest.NewRecorder()

	// Initialize a new dummy http.Request
	r, err := http.NewRequest(http.MethodGet, "/", nil)
	if err != nil {
		// t.Fatal() function in handles situations where there is an
		// unexpected error in the test code. When called, t.Fatal() will
		// mark the test as failed, log the error, and then completely stop
		// execution of the current test (or sub-test). It should typically
		// called in situations where it doesn't make sense to continue the
		// current test -- such as an error during setup step, or when an
		// unexpected error from a Go standard library function means one
		// can't proceed with the test.
		t.Fatal(err)
	}

	// Call the ping handler function, passing it the
	// httptest.ResponseRecorder and http.Request
	ping(rr, r)

	// Call the Result() method on the http.ResponseRecorder
	// to get the http.Response generated by the ping handler
	rs := rr.Result()

	// Check that the status code written byy the ping handler
	// was 200
	assert.Equal(t, rs.StatusCode, http.StatusOK)

	// And also check that the response body written by the
	// ping handler equals "OK"
	defer rs.Body.Close()
	body, err := io.ReadAll(rs.Body)
	if err != nil {
		t.Fatal(err)
	}
	bytes.TrimSpace(body)

	assert.Equal(t, string(body), "OK")

}
